# Generated by Django 5.0.2 on 2024-03-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
